enableColors: true

networkConcurrency: "1,"

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com/"

packageExtensions:
  react-app-rewired@*:
    dependencies:
      react-dev-utils: ^12.0.1

yarnPath: .yarn/releases/yarn-4.3.1.js
