nodeLinker: "node-modules"
npmRegistryServer: "https://registry.yarnpkg.com/"
enableColors: true
packageExtensions:
  "react-app-rewired@*":
    dependencies:
      "react-dev-utils": "^12.0.1"
  "@clutch-sh/dynamodb@*":
    dependencies:
      "esbuild": "^0.18.0"
  "@clutch-sh/ec2@*":
    dependencies:
      "esbuild": "^0.18.0"
  "@clutch-sh/k8s@*":
    dependencies:
      "esbuild": "^0.18.0"
  "@clutch-sh/kinesis@*":
    dependencies:
      "esbuild": "^0.18.0"
  "@clutch-sh/project-selector@*":
    dependencies:
      "esbuild": "^0.18.0"
  "@clutch-sh/redis-experimentation@*":
    dependencies:
      "esbuild": "^0.18.0"
  "@clutch-sh/server-experimentation@*":
    dependencies:
      "esbuild": "^0.18.0"
  "@clutch-sh/sourcecontrol@*":
    dependencies:
      "esbuild": "^0.18.0"
