networkConcurrency: "1,"
nodeLinker: "pnpm"
pnpFallbackMode: "all"
pnpMode: "loose"
enableColors: true
# nodeLinker: "node-modules"
# nmHoistingLimits: "workspaces"
npmRegistryServer: "https://registry.yarnpkg.com/"
packageExtensions:
  "react-app-rewired@*":
    dependencies:
      "react-dev-utils": "^12.0.1"
