networkConcurrency: "1,"
enableColors: true
nodeLinker: "node-modules"
npmRegistryServer: "https://registry.yarnpkg.com/"
packageExtensions:
  "react-app-rewired@*":
    dependencies:
      "react-dev-utils": "^12.0.1"
