// COLORS FROM FIGMA
// NOTE THAT THOSE WITH GRADIENTS ONLY HAVE THEIR BASES

// LIGHT MODE COLORS ////////////////////////////////////////////////////////

// NEUTRAL
export const CLUTCH_LIGHTMODE_NEUTRAL_5="#F8F8F9"; // PRIMARY BUTTON DISABLED / STROKE TERTIARY
export const CLUTCH_LIGHTMODE_NEUTRAL_10="#E7E7EA";
export const CLUTCH_LIGHTMODE_NEUTRAL_12="#E2E2E6"; // SECONDARY BUTTON PRESSED / FOCUSED
export const CLUTCH_LIGHTMODE_NEUTRAL_15="#DBDBE0";
export const CLUTCH_LIGHTMODE_NEUTRAL_20="#CFCFD6";
export const CLUTCH_LIGHTMODE_NEUTRAL_25="#C2C3CB";
export const CLUTCH_LIGHTMODE_NEUTRAL_30="#A3A4B0"; // STROKE SECONDARY / TEXT TERTIARY
export const CLUTCH_LIGHTMODE_NEUTRAL_40="#868797";
export const CLUTCH_LIGHTMODE_NEUTRAL_50="#6E7083"; // TEXT SECONDARY
export const CLUTCH_LIGHTMODE_NEUTRAL_60="#56586E";
export const CLUTCH_LIGHTMODE_NEUTRAL_70="#494C64";
export const CLUTCH_LIGHTMODE_NEUTRAL_80="#31344F";
export const CLUTCH_LIGHTMODE_NEUTRAL_90="#1E213E";
export const CLUTCH_LIGHTMODE_NEUTRAL_100="#0D1030";

// BLUE
export const CLUTCH_LIGHTMODE_BLUE_10="#F9F9FE";
export const CLUTCH_LIGHTMODE_BLUE_20="#F5F6FD";
export const CLUTCH_LIGHTMODE_BLUE_30="#EBEDFB";
export const CLUTCH_LIGHTMODE_BLUE_40="#D7DAF6";
export const CLUTCH_LIGHTMODE_BLUE_50="#C2C8F2";
export const CLUTCH_LIGHTMODE_BLUE_60="#727FE1";
export const CLUTCH_LIGHTMODE_BLUE_70="#3548D4";
export const CLUTCH_LIGHTMODE_BLUE_80="#1629B9";
export const CLUTCH_LIGHTMODE_BLUE_90="#0A1CA6";
export const CLUTCH_LIGHTMODE_BLUE_100="#011082";

// GREEN
export const CLUTCH_LIGHTMODE_GREEN_10="#E5FCE8";
export const CLUTCH_LIGHTMODE_GREEN_20="#CBF7CF";
export const CLUTCH_LIGHTMODE_GREEN_30="#ACF2B2";
export const CLUTCH_LIGHTMODE_GREEN_40="#6CD47A";
export const CLUTCH_LIGHTMODE_GREEN_50="#4AB958";
export const CLUTCH_LIGHTMODE_GREEN_60="#32A140";
export const CLUTCH_LIGHTMODE_GREEN_70="#1C872A";
export const CLUTCH_LIGHTMODE_GREEN_80="#106E1D";
export const CLUTCH_LIGHTMODE_GREEN_90="#086515";
export const CLUTCH_LIGHTMODE_GREEN_100="#02590E";

// AMBER
export const CLUTCH_LIGHTMODE_AMBER_10="#FFFBEB";
export const CLUTCH_LIGHTMODE_AMBER_20="#FEF3C7";
export const CLUTCH_LIGHTMODE_AMBER_30="#FDE68A";
export const CLUTCH_LIGHTMODE_AMBER_40="#FCD34D";
export const CLUTCH_LIGHTMODE_AMBER_50="#FBBF24";
export const CLUTCH_LIGHTMODE_AMBER_60="#F59E0B";
export const CLUTCH_LIGHTMODE_AMBER_70="#D97706";
export const CLUTCH_LIGHTMODE_AMBER_80="#B45309";
export const CLUTCH_LIGHTMODE_AMBER_90="#92400E";
export const CLUTCH_LIGHTMODE_AMBER_100="#78350F";

// RED
export const CLUTCH_LIGHTMODE_RED_10="#FDE9E7";
export const CLUTCH_LIGHTMODE_RED_20="#FBDAD6";
export const CLUTCH_LIGHTMODE_RED_30="#F5BFBA";
export const CLUTCH_LIGHTMODE_RED_40="#F4AAA3";
export const CLUTCH_LIGHTMODE_RED_50="#F38D84";
export const CLUTCH_LIGHTMODE_RED_60="#E95F52";
export const CLUTCH_LIGHTMODE_RED_70="#DB3615";
export const CLUTCH_LIGHTMODE_RED_80="#C3290B";
export const CLUTCH_LIGHTMODE_RED_90="#A11E05";
export const CLUTCH_LIGHTMODE_RED_100="#811500";

// TYPOGRAPHY AND ICONS
export const CLUTCH_LIGHTMODE_PRIMARY     = "#0D1030";
export const CLUTCH_LIGHTMODE_SECONDARY   = "#0D103099";
export const CLUTCH_LIGHTMODE_TERTIARY    = "#0D103061";
export const CLUTCH_LIGHTMODE_INTERACTIVE = "#3548D4";
export const CLUTCH_LIGHTMODE_NEGATIVE    = "#DB3615";
export const CLUTCH_LIGHTMODE_POSITIVE    = "#1C872A";
export const CLUTCH_LIGHTMODE_INVERSE     = "#FFFFFF";

// STROKE
export const CLUTCH_LIGHTMODE_STROKE_PRIMARY   = "#0D1030";
export const CLUTCH_LIGHTMODE_STROKE_SECONDARY = "#0D103061";
export const CLUTCH_LIGHTMODE_STROKE_TERTIARY  = "#0D10301A";
export const CLUTCH_LIGHTMODE_STROKE_INVERSE   = "#FFFFFF";

// BACKGROUND
export const CLUTCH_LIGHTMODE_BACKGROUND_PRIMARY   = "#FFFFFF";
export const CLUTCH_LIGHTMODE_BACKGROUND_SECONDARY = "#F9FAFE";

// STATES
export const CLUTCH_LIGHTMODE_STATES_PRIMARY_HOVER    = "#3548D41A";
export const CLUTCH_LIGHTMODE_STATES_PRIMARY_FOCUSED  = "#3548D40D";
export const CLUTCH_LIGHTMODE_STATES_PRIMARY_PRESSED  = "#3548D426";
export const CLUTCH_LIGHTMODE_STATES_PRIMARY_SELECTED = "#3548D433";
export const CLUTCH_LIGHTMODE_STATES_NEUTRAL_HOVER    = "#0D10301A";
export const CLUTCH_LIGHTMODE_STATES_NEUTRAL_FOCUSED  = "#0D10300D";
export const CLUTCH_LIGHTMODE_STATES_NEUTRAL_PRESSED  = "#0D103021";
export const CLUTCH_LIGHTMODE_STATES_NEUTRAL_SELECTED = "#0D103026";


// DARK MODE COLORS ////////////////////////////////////////////////////////

// NEUTRAL
export const CLUTCH_DARKMODE_NEUTRAL_5 = "#272946"; // PRIMARY BUTTON DISABLED / STROKE TERTIARY
export const CLUTCH_DARKMODE_NEUTRAL_10 = "#33344F";
export const CLUTCH_DARKMODE_NEUTRAL_12 = "#373953"; // SECONDARY BUTTON PRESSED / FOCUSED
export const CLUTCH_DARKMODE_NEUTRAL_15 = "#3E4059";
export const CLUTCH_DARKMODE_NEUTRAL_20 = "#494B63";
export const CLUTCH_DARKMODE_NEUTRAL_25 = "#55566D";
export const CLUTCH_DARKMODE_NEUTRAL_30 = "#606176"; // STROKE SECONDARY / TEXT TERTIARY
export const CLUTCH_DARKMODE_NEUTRAL_40 = "#77788A";
export const CLUTCH_DARKMODE_NEUTRAL_50 = "#8D8E9D"; // TEXT SECONDARY
export const CLUTCH_DARKMODE_NEUTRAL_60 = "#A4A5B1";
export const CLUTCH_DARKMODE_NEUTRAL_70 = "#B0B0BB";
export const CLUTCH_DARKMODE_NEUTRAL_80 = "#BBBBC4";
export const CLUTCH_DARKMODE_NEUTRAL_90 = "#D2D2D8";
export const CLUTCH_DARKMODE_NEUTRAL_100 = "#E8E8EB";

// BLUE
export const CLUTCH_DARKMODE_BLUE_10 = "#050653"; // BG
export const CLUTCH_DARKMODE_BLUE_20 = "#060869"; // HOVER
export const CLUTCH_DARKMODE_BLUE_30 = "#13117C"; // FOCUSED
export const CLUTCH_DARKMODE_BLUE_40 = "#161DBC"; // PRESSED
export const CLUTCH_DARKMODE_BLUE_50 = "#2A4FF6";
export const CLUTCH_DARKMODE_BLUE_60 = "#4281F6";
export const CLUTCH_DARKMODE_BLUE_70 = "#5AABF6";
export const CLUTCH_DARKMODE_BLUE_80 = "#8CC4F8";
export const CLUTCH_DARKMODE_BLUE_90 = "#C2E1FE";
export const CLUTCH_DARKMODE_BLUE_100 = "#DCECFB";

// GREEN
export const CLUTCH_DARKMODE_GREEN_10= "#00580B";
export const CLUTCH_DARKMODE_GREEN_20= "#0D7620";
export const CLUTCH_DARKMODE_GREEN_30= "#1C872A";
export const CLUTCH_DARKMODE_GREEN_40= "#299935";
export const CLUTCH_DARKMODE_GREEN_50= "#32A73E";
export const CLUTCH_DARKMODE_GREEN_60= "#54B45B";
export const CLUTCH_DARKMODE_GREEN_70= "#73C178";
export const CLUTCH_DARKMODE_GREEN_80= "#9CD29E";
export const CLUTCH_DARKMODE_GREEN_90= "#C3E4C4";
export const CLUTCH_DARKMODE_GREEN_100="#E6F4E7";

// AMBER
export const CLUTCH_DARKMODE_AMBER_10="#6B442A";
export const CLUTCH_DARKMODE_AMBER_20="#D26803";
export const CLUTCH_DARKMODE_AMBER_30="#D97706";
export const CLUTCH_DARKMODE_AMBER_40="#DF850A";
export const CLUTCH_DARKMODE_AMBER_50="#E3900E";
export const CLUTCH_DARKMODE_AMBER_60="#E69F2A";
export const CLUTCH_DARKMODE_AMBER_70="#EAB04E";
export const CLUTCH_DARKMODE_AMBER_80="#EFC67F";
export const CLUTCH_DARKMODE_AMBER_90="#F6DCB1";
export const CLUTCH_DARKMODE_AMBER_100="#FBF1E0";

// RED
export const CLUTCH_DARKMODE_RED_10= "#6C1404";
export const CLUTCH_DARKMODE_RED_20= "#DB3615";
export const CLUTCH_DARKMODE_RED_30= "#E93D19";
export const CLUTCH_DARKMODE_RED_40= "#F7441F";
export const CLUTCH_DARKMODE_RED_50= "#FF4A23";
export const CLUTCH_DARKMODE_RED_60= "#FF6843";
export const CLUTCH_DARKMODE_RED_70= "#FF8464";
export const CLUTCH_DARKMODE_RED_80= "#FFA790";
export const CLUTCH_DARKMODE_RED_90= "#FFCABC";
export const CLUTCH_DARKMODE_RED_100="#FBE8E7";

// TYPOGRAPHY AND ICONS
export const CLUTCH_DARKMODE_PRIMARY     = "#FFFFFFE5";
export const CLUTCH_DARKMODE_SECONDARY   = "#FFFFFFBF";
export const CLUTCH_DARKMODE_TERTIARY    = "#FFFFFF61";
export const CLUTCH_DARKMODE_INTERACTIVE = "#3548D4";
export const CLUTCH_DARKMODE_NEGATIVE    = "#DB3615";
export const CLUTCH_DARKMODE_POSITIVE    = "#1C872A";
export const CLUTCH_DARKMODE_INVERSE     = "#0D1030";

// STROKE
export const CLUTCH_DARKMODE_STROKE_PRIMARY   = "#FFFFFFDE";
export const CLUTCH_DARKMODE_STROKE_SECONDARY = "#FFFFFF73";
export const CLUTCH_DARKMODE_STROKE_TERTIARY  = "#FFFFFF40";
export const CLUTCH_DARKMODE_STROKE_INVERSE     = "#0D1030";

// BACKGROUND
export const CLUTCH_DARKMODE_BACKGROUND_PRIMARY   = "#FFFFFF0F";
export const CLUTCH_DARKMODE_BACKGROUND_SECONDARY = "#0D1030";
export const CLUTCH_DARKMODE_BACKGROUND_INVERSE     = "#0D1030";

// STATES
export const CLUTCH_DARKMODE_STATES_PRIMARY_HOVER    = "#5AABF60D";
export const CLUTCH_DARKMODE_STATES_PRIMARY_FOCUSED  = "#5AABF61A";
export const CLUTCH_DARKMODE_STATES_PRIMARY_PRESSED  = "#5AABF626";
export const CLUTCH_DARKMODE_STATES_PRIMARY_SELECTED = "#5AABF633";
export const CLUTCH_DARKMODE_STATES_NEUTRAL_HOVER    = "#FFFFFF12";
export const CLUTCH_DARKMODE_STATES_NEUTRAL_FOCUSED  = "#FFFFFF1F";
export const CLUTCH_DARKMODE_STATES_NEUTRAL_PRESSED  = "#FFFFFF2E";
export const CLUTCH_DARKMODE_STATES_NEUTRAL_SELECTED = "#FFFFFF40";












// COLORS NOT IN FIGMA ////////////////////////////////////////////////////////