# https://github.com/golangci/golangci-lint
linters:
  disable-all: true
  enable:
  - deadcode
  - errcheck
  - gocritic
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - scopelint
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - whitespace
  - varcheck
linters-settings:
  goimports:
    local-prefixes: github.com/lyft/clutch/backend
  gocritic:
    disabled-checks:
      - singleCaseSwitch
issues:
  max-per-linter: 0
  max-same-issues: 0
run:
  timeout: 5m
  skip-dirs:
    - api/
