# https://github.com/golangci/golangci-lint
linters:
  disable-all: true
  enable:
  - errcheck
  - copyloopvar
  - gci
  - gocritic
  - gofmt
  - gosec
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused
  - whitespace
linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/lyft/clutch/backend)
  gosec:
    excludes:
      # Flags for potentially-unsafe casting of ints, similar problem to globally-disabled G103
      - G115
issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: (_test\.go|mock\.go)
      linters:
        - gosec
    # TODO: remove this rule once the migration to the new protobuf APIs are complete
    - text: "^SA1019.*?(github.com/golang/protobuf/proto|github.com/golang/protobuf/ptypes).*?deprecated"
      linters:
        - staticcheck
run:
  timeout: 10m
  skip-dirs:
    - api/
