# https://github.com/golangci/golangci-lint
linters:
  disable-all: true
  enable:
  - deadcode
  - gci
  - errcheck
  - gocritic
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - scopelint
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - whitespace
  - varcheck
linters-settings:
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  goimports:
    local-prefixes: github.com/lyft/clutch/backend
issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: (_test\.go|mock\.go)
      linters:
        - gosec
    # TODO: remove this rule once the migration to the new protobuf APIs are complete
    - text: "^SA1019.*?(ptypes\\.(Duration|Timestamp|DynamicAny)|github.com/golang/protobuf/proto|github.com/golang/protobuf/ptypes).*?deprecated"
      linters:
        - staticcheck
run:
  timeout: 5m
  skip-dirs:
    - api/
