// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: play/v1/play.proto

package playv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Play_Type int32

const (
	Play_UNSPECIFIED Play_Type = 0
	Play_CARD        Play_Type = 1
	Play_FIGURE      Play_Type = 2
	Play_YARN        Play_Type = 3
)

// Enum value maps for Play_Type.
var (
	Play_Type_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CARD",
		2: "FIGURE",
		3: "YARN",
	}
	Play_Type_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CARD":        1,
		"FIGURE":      2,
		"YARN":        3,
	}
)

func (x Play_Type) Enum() *Play_Type {
	p := new(Play_Type)
	*p = x
	return p
}

func (x Play_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Play_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_play_v1_play_proto_enumTypes[0].Descriptor()
}

func (Play_Type) Type() protoreflect.EnumType {
	return &file_play_v1_play_proto_enumTypes[0]
}

func (x Play_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Play_Type.Descriptor instead.
func (Play_Type) EnumDescriptor() ([]byte, []int) {
	return file_play_v1_play_proto_rawDescGZIP(), []int{2, 0}
}

type GetPlayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPlayRequest) Reset() {
	*x = GetPlayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_play_v1_play_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayRequest) ProtoMessage() {}

func (x *GetPlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_play_v1_play_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayRequest.ProtoReflect.Descriptor instead.
func (*GetPlayRequest) Descriptor() ([]byte, []int) {
	return file_play_v1_play_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPlayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Play []*Play `protobuf:"bytes,1,rep,name=play,proto3" json:"play,omitempty"`
}

func (x *GetPlayResponse) Reset() {
	*x = GetPlayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_play_v1_play_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayResponse) ProtoMessage() {}

func (x *GetPlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_play_v1_play_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayResponse.ProtoReflect.Descriptor instead.
func (*GetPlayResponse) Descriptor() ([]byte, []int) {
	return file_play_v1_play_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayResponse) GetPlay() []*Play {
	if x != nil {
		return x.Play
	}
	return nil
}

type Play struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Character string    `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	Name      string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Series    string    `protobuf:"bytes,3,opt,name=series,proto3" json:"series,omitempty"`
	ImageUrl  string    `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Type      Play_Type `protobuf:"varint,5,opt,name=type,proto3,enum=clutch.play.v1.Play_Type" json:"type,omitempty"`
}

func (x *Play) Reset() {
	*x = Play{}
	if protoimpl.UnsafeEnabled {
		mi := &file_play_v1_play_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Play) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Play) ProtoMessage() {}

func (x *Play) ProtoReflect() protoreflect.Message {
	mi := &file_play_v1_play_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Play.ProtoReflect.Descriptor instead.
func (*Play) Descriptor() ([]byte, []int) {
	return file_play_v1_play_proto_rawDescGZIP(), []int{2}
}

func (x *Play) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *Play) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Play) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *Play) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Play) GetType() Play_Type {
	if x != nil {
		return x.Type
	}
	return Play_UNSPECIFIED
}

var File_play_v1_play_proto protoreflect.FileDescriptor

var file_play_v1_play_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x20, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x04, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c,
	0x75, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x79, 0x22, 0xd5, 0x01, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x79,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2e, 0x70,
	0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f,
	0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x43, 0x41, 0x52, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x49, 0x47,
	0x55, 0x52, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x59, 0x41, 0x52, 0x4e, 0x10, 0x03, 0x32,
	0x72, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x41, 0x50, 0x49, 0x12, 0x67, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x1e, 0x2e, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2e, 0x70,
	0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2e, 0x70,
	0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x10,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79,
	0x3a, 0x01, 0x2a, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x79, 0x66, 0x74, 0x2f, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x76,
	0x31, 0x2f, 0x3b, 0x70, 0x6c, 0x61, 0x79, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_play_v1_play_proto_rawDescOnce sync.Once
	file_play_v1_play_proto_rawDescData = file_play_v1_play_proto_rawDesc
)

func file_play_v1_play_proto_rawDescGZIP() []byte {
	file_play_v1_play_proto_rawDescOnce.Do(func() {
		file_play_v1_play_proto_rawDescData = protoimpl.X.CompressGZIP(file_play_v1_play_proto_rawDescData)
	})
	return file_play_v1_play_proto_rawDescData
}

var file_play_v1_play_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_play_v1_play_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_play_v1_play_proto_goTypes = []interface{}{
	(Play_Type)(0),          // 0: clutch.play.v1.Play.Type
	(*GetPlayRequest)(nil),  // 1: clutch.play.v1.GetPlayRequest
	(*GetPlayResponse)(nil), // 2: clutch.play.v1.GetPlayResponse
	(*Play)(nil),            // 3: clutch.play.v1.Play
}
var file_play_v1_play_proto_depIdxs = []int32{
	3, // 0: clutch.play.v1.GetPlayResponse.play:type_name -> clutch.play.v1.Play
	0, // 1: clutch.play.v1.Play.type:type_name -> clutch.play.v1.Play.Type
	1, // 2: clutch.play.v1.PlayAPI.GetPlay:input_type -> clutch.play.v1.GetPlayRequest
	2, // 3: clutch.play.v1.PlayAPI.GetPlay:output_type -> clutch.play.v1.GetPlayResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_play_v1_play_proto_init() }
func file_play_v1_play_proto_init() {
	if File_play_v1_play_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_play_v1_play_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_play_v1_play_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_play_v1_play_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Play); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_play_v1_play_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_play_v1_play_proto_goTypes,
		DependencyIndexes: file_play_v1_play_proto_depIdxs,
		EnumInfos:         file_play_v1_play_proto_enumTypes,
		MessageInfos:      file_play_v1_play_proto_msgTypes,
	}.Build()
	File_play_v1_play_proto = out.File
	file_play_v1_play_proto_rawDesc = nil
	file_play_v1_play_proto_goTypes = nil
	file_play_v1_play_proto_depIdxs = nil
}
