// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: config/module/chaos/serverexperimentation/rtds/v1/rtds.proto

package xdsv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _rtds_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on ServerFaultsRTDSResourceGeneratorConfig
// with the rules defined in the proto definition for this message. If any
// rules are violated, an error is returned.
func (m *ServerFaultsRTDSResourceGeneratorConfig) Validate() error {
	if m == nil {
		return nil
	}

	if len(m.GetIngressFaultRuntimePrefix()) < 1 {
		return ServerFaultsRTDSResourceGeneratorConfigValidationError{
			field:  "IngressFaultRuntimePrefix",
			reason: "value length must be at least 1 bytes",
		}
	}

	if len(m.GetEgressFaultRuntimePrefix()) < 1 {
		return ServerFaultsRTDSResourceGeneratorConfigValidationError{
			field:  "EgressFaultRuntimePrefix",
			reason: "value length must be at least 1 bytes",
		}
	}

	return nil
}

// ServerFaultsRTDSResourceGeneratorConfigValidationError is the validation
// error returned by ServerFaultsRTDSResourceGeneratorConfig.Validate if the
// designated constraints aren't met.
type ServerFaultsRTDSResourceGeneratorConfigValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServerFaultsRTDSResourceGeneratorConfigValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServerFaultsRTDSResourceGeneratorConfigValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServerFaultsRTDSResourceGeneratorConfigValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServerFaultsRTDSResourceGeneratorConfigValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServerFaultsRTDSResourceGeneratorConfigValidationError) ErrorName() string {
	return "ServerFaultsRTDSResourceGeneratorConfigValidationError"
}

// Error satisfies the builtin error interface
func (e ServerFaultsRTDSResourceGeneratorConfigValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServerFaultsRTDSResourceGeneratorConfig.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServerFaultsRTDSResourceGeneratorConfigValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServerFaultsRTDSResourceGeneratorConfigValidationError{}
