// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaos/serverexperimentation/v1/serverexperimentation.proto

package serverexperimentationv1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/lyft/clutch/backend/api/api/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestSpecification struct {
	// Types that are valid to be assigned to Config:
	//	*TestSpecification_Abort
	//	*TestSpecification_Latency
	Config               isTestSpecification_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TestSpecification) Reset()         { *m = TestSpecification{} }
func (m *TestSpecification) String() string { return proto.CompactTextString(m) }
func (*TestSpecification) ProtoMessage()    {}
func (*TestSpecification) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fa9b5aa8ec02b3d, []int{0}
}

func (m *TestSpecification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestSpecification.Unmarshal(m, b)
}
func (m *TestSpecification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestSpecification.Marshal(b, m, deterministic)
}
func (m *TestSpecification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestSpecification.Merge(m, src)
}
func (m *TestSpecification) XXX_Size() int {
	return xxx_messageInfo_TestSpecification.Size(m)
}
func (m *TestSpecification) XXX_DiscardUnknown() {
	xxx_messageInfo_TestSpecification.DiscardUnknown(m)
}

var xxx_messageInfo_TestSpecification proto.InternalMessageInfo

type isTestSpecification_Config interface {
	isTestSpecification_Config()
}

type TestSpecification_Abort struct {
	Abort *AbortFault `protobuf:"bytes,2,opt,name=abort,proto3,oneof"`
}

type TestSpecification_Latency struct {
	Latency *LatencyFault `protobuf:"bytes,3,opt,name=latency,proto3,oneof"`
}

func (*TestSpecification_Abort) isTestSpecification_Config() {}

func (*TestSpecification_Latency) isTestSpecification_Config() {}

func (m *TestSpecification) GetConfig() isTestSpecification_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *TestSpecification) GetAbort() *AbortFault {
	if x, ok := m.GetConfig().(*TestSpecification_Abort); ok {
		return x.Abort
	}
	return nil
}

func (m *TestSpecification) GetLatency() *LatencyFault {
	if x, ok := m.GetConfig().(*TestSpecification_Latency); ok {
		return x.Latency
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TestSpecification) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TestSpecification_Abort)(nil),
		(*TestSpecification_Latency)(nil),
	}
}

// Targets requests from downstream_cluster -> upstream_cluster
type ClusterPairTarget struct {
	// The name of the downstream cluster
	DownstreamCluster string `protobuf:"bytes,1,opt,name=downstream_cluster,json=downstreamCluster,proto3" json:"downstream_cluster,omitempty"`
	// The name of the upstream cluster
	UpstreamCluster      string   `protobuf:"bytes,2,opt,name=upstream_cluster,json=upstreamCluster,proto3" json:"upstream_cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterPairTarget) Reset()         { *m = ClusterPairTarget{} }
func (m *ClusterPairTarget) String() string { return proto.CompactTextString(m) }
func (*ClusterPairTarget) ProtoMessage()    {}
func (*ClusterPairTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fa9b5aa8ec02b3d, []int{1}
}

func (m *ClusterPairTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterPairTarget.Unmarshal(m, b)
}
func (m *ClusterPairTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterPairTarget.Marshal(b, m, deterministic)
}
func (m *ClusterPairTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterPairTarget.Merge(m, src)
}
func (m *ClusterPairTarget) XXX_Size() int {
	return xxx_messageInfo_ClusterPairTarget.Size(m)
}
func (m *ClusterPairTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterPairTarget.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterPairTarget proto.InternalMessageInfo

func (m *ClusterPairTarget) GetDownstreamCluster() string {
	if m != nil {
		return m.DownstreamCluster
	}
	return ""
}

func (m *ClusterPairTarget) GetUpstreamCluster() string {
	if m != nil {
		return m.UpstreamCluster
	}
	return ""
}

type AbortFault struct {
	// Types that are valid to be assigned to Target:
	//	*AbortFault_ClusterPair
	Target isAbortFault_Target `protobuf_oneof:"target"`
	// The percentage of requests that will be faulted.
	Percent float32 `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"`
	// The abort HTTP status that will be returned.
	HttpStatus           int32    `protobuf:"varint,3,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AbortFault) Reset()         { *m = AbortFault{} }
func (m *AbortFault) String() string { return proto.CompactTextString(m) }
func (*AbortFault) ProtoMessage()    {}
func (*AbortFault) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fa9b5aa8ec02b3d, []int{2}
}

func (m *AbortFault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AbortFault.Unmarshal(m, b)
}
func (m *AbortFault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AbortFault.Marshal(b, m, deterministic)
}
func (m *AbortFault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AbortFault.Merge(m, src)
}
func (m *AbortFault) XXX_Size() int {
	return xxx_messageInfo_AbortFault.Size(m)
}
func (m *AbortFault) XXX_DiscardUnknown() {
	xxx_messageInfo_AbortFault.DiscardUnknown(m)
}

var xxx_messageInfo_AbortFault proto.InternalMessageInfo

type isAbortFault_Target interface {
	isAbortFault_Target()
}

type AbortFault_ClusterPair struct {
	ClusterPair *ClusterPairTarget `protobuf:"bytes,1,opt,name=cluster_pair,json=clusterPair,proto3,oneof"`
}

func (*AbortFault_ClusterPair) isAbortFault_Target() {}

func (m *AbortFault) GetTarget() isAbortFault_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *AbortFault) GetClusterPair() *ClusterPairTarget {
	if x, ok := m.GetTarget().(*AbortFault_ClusterPair); ok {
		return x.ClusterPair
	}
	return nil
}

func (m *AbortFault) GetPercent() float32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *AbortFault) GetHttpStatus() int32 {
	if m != nil {
		return m.HttpStatus
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AbortFault) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AbortFault_ClusterPair)(nil),
	}
}

type LatencyFault struct {
	// Types that are valid to be assigned to Target:
	//	*LatencyFault_ClusterPair
	Target isLatencyFault_Target `protobuf_oneof:"target"`
	// The percentage of requests that will be slowed down.
	Percent float32 `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"`
	// The latency duration in milliseconds.
	DurationMs           int32    `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatencyFault) Reset()         { *m = LatencyFault{} }
func (m *LatencyFault) String() string { return proto.CompactTextString(m) }
func (*LatencyFault) ProtoMessage()    {}
func (*LatencyFault) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fa9b5aa8ec02b3d, []int{3}
}

func (m *LatencyFault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatencyFault.Unmarshal(m, b)
}
func (m *LatencyFault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatencyFault.Marshal(b, m, deterministic)
}
func (m *LatencyFault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatencyFault.Merge(m, src)
}
func (m *LatencyFault) XXX_Size() int {
	return xxx_messageInfo_LatencyFault.Size(m)
}
func (m *LatencyFault) XXX_DiscardUnknown() {
	xxx_messageInfo_LatencyFault.DiscardUnknown(m)
}

var xxx_messageInfo_LatencyFault proto.InternalMessageInfo

type isLatencyFault_Target interface {
	isLatencyFault_Target()
}

type LatencyFault_ClusterPair struct {
	ClusterPair *ClusterPairTarget `protobuf:"bytes,1,opt,name=cluster_pair,json=clusterPair,proto3,oneof"`
}

func (*LatencyFault_ClusterPair) isLatencyFault_Target() {}

func (m *LatencyFault) GetTarget() isLatencyFault_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *LatencyFault) GetClusterPair() *ClusterPairTarget {
	if x, ok := m.GetTarget().(*LatencyFault_ClusterPair); ok {
		return x.ClusterPair
	}
	return nil
}

func (m *LatencyFault) GetPercent() float32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *LatencyFault) GetDurationMs() int32 {
	if m != nil {
		return m.DurationMs
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LatencyFault) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LatencyFault_ClusterPair)(nil),
	}
}

func init() {
	proto.RegisterType((*TestSpecification)(nil), "clutch.chaos.serverexperimentation.v1.TestSpecification")
	proto.RegisterType((*ClusterPairTarget)(nil), "clutch.chaos.serverexperimentation.v1.ClusterPairTarget")
	proto.RegisterType((*AbortFault)(nil), "clutch.chaos.serverexperimentation.v1.AbortFault")
	proto.RegisterType((*LatencyFault)(nil), "clutch.chaos.serverexperimentation.v1.LatencyFault")
}

func init() {
	proto.RegisterFile("chaos/serverexperimentation/v1/serverexperimentation.proto", fileDescriptor_9fa9b5aa8ec02b3d)
}

var fileDescriptor_9fa9b5aa8ec02b3d = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x27, 0x71, 0xbb, 0xd5, 0x97, 0xc2, 0x6e, 0xe7, 0xb2, 0xb5, 0x28, 0x84, 0xc2, 0x42,
	0x45, 0x48, 0x48, 0x17, 0x44, 0xbc, 0x39, 0x82, 0xac, 0xa0, 0x28, 0xd9, 0x3d, 0x09, 0x52, 0x66,
	0xa7, 0xb3, 0xed, 0x40, 0x9a, 0x09, 0x33, 0x2f, 0x51, 0x4f, 0x7e, 0x2e, 0xbf, 0x81, 0x07, 0xbd,
	0xfb, 0x59, 0x7a, 0x92, 0x4c, 0x12, 0xba, 0xda, 0x1e, 0x7a, 0xf4, 0x56, 0xfa, 0x7b, 0xff, 0xdf,
	0xcc, 0xff, 0x4d, 0xe0, 0x85, 0x58, 0x71, 0x6d, 0x63, 0x2b, 0x4d, 0x25, 0x8d, 0xfc, 0x52, 0x48,
	0xa3, 0xd6, 0x32, 0x47, 0x8e, 0x4a, 0xe7, 0x71, 0x95, 0xec, 0x07, 0x51, 0x61, 0x34, 0x6a, 0x7a,
	0x2e, 0xb2, 0x12, 0xc5, 0x2a, 0x72, 0x8a, 0x68, 0xff, 0x64, 0x95, 0x8c, 0x1f, 0x2d, 0xb5, 0x5e,
	0x66, 0x32, 0xe6, 0x85, 0x8a, 0x79, 0x9e, 0xeb, 0x86, 0xd8, 0x46, 0x32, 0x3e, 0xab, 0x78, 0xa6,
	0x16, 0x1c, 0x65, 0xdc, 0xfd, 0x68, 0xc1, 0xa8, 0x9e, 0xaf, 0x92, 0xdd, 0xc8, 0xe4, 0xbb, 0x07,
	0xc3, 0x6b, 0x69, 0xf1, 0xaa, 0x90, 0x42, 0xdd, 0x2a, 0xe1, 0x20, 0x7d, 0x03, 0x3d, 0x7e, 0xa3,
	0x0d, 0x8e, 0xfc, 0xd0, 0x9b, 0x06, 0xb3, 0x24, 0x3a, 0xe8, 0x76, 0xd1, 0xcb, 0x3a, 0xf3, 0x9a,
	0x97, 0x19, 0x5e, 0x92, 0xb4, 0x31, 0xd0, 0xf7, 0xd0, 0xcf, 0x38, 0xca, 0x5c, 0x7c, 0x1d, 0xdd,
	0x73, 0xb2, 0x8b, 0x03, 0x65, 0x6f, 0x9b, 0x54, 0xa7, 0xeb, 0x2c, 0xec, 0x3e, 0x1c, 0x0b, 0x9d,
	0xdf, 0xaa, 0xe5, 0xe4, 0x1b, 0x0c, 0x5f, 0x65, 0xa5, 0x45, 0x69, 0x3e, 0x70, 0x65, 0xae, 0xb9,
	0x59, 0x4a, 0xa4, 0xcf, 0x80, 0x2e, 0xf4, 0xe7, 0xdc, 0xa2, 0x91, 0x7c, 0x3d, 0x17, 0x0d, 0x1f,
	0x79, 0xa1, 0x37, 0x7d, 0xc0, 0xfa, 0x1b, 0x76, 0x64, 0xfc, 0xd0, 0x4b, 0x87, 0xdb, 0x91, 0xd6,
	0x40, 0x67, 0x70, 0x5a, 0x16, 0xff, 0xa4, 0xfc, 0xbf, 0x53, 0x27, 0xdd, 0x40, 0x9b, 0x99, 0xfc,
	0xf2, 0x00, 0xb6, 0x9d, 0xe9, 0x27, 0x18, 0xb4, 0xc9, 0x79, 0xc1, 0x55, 0x73, 0x68, 0x30, 0x7b,
	0x7e, 0x60, 0xdf, 0x9d, 0x2a, 0x97, 0x24, 0x0d, 0xc4, 0xf6, 0x4f, 0xfa, 0x04, 0xfa, 0x85, 0x34,
	0x42, 0xe6, 0xcd, 0xb3, 0xf8, 0xec, 0x64, 0xc3, 0x06, 0x00, 0x8f, 0x09, 0xf9, 0xc1, 0xce, 0x09,
	0x21, 0x24, 0xed, 0x38, 0x7d, 0x0a, 0xc1, 0x0a, 0xb1, 0x98, 0x5b, 0xe4, 0x58, 0x5a, 0xb7, 0xf8,
	0x1e, 0x83, 0x0d, 0xeb, 0x8f, 0x7b, 0xa7, 0xbf, 0x8f, 0x42, 0x91, 0x42, 0x8d, 0xaf, 0x1c, 0xad,
	0x17, 0x8a, 0xee, 0xc0, 0xc9, 0x4f, 0x0f, 0x06, 0x77, 0xd7, 0xfe, 0x1f, 0x35, 0x9a, 0x42, 0xb0,
	0x28, 0x8d, 0x53, 0xcf, 0xd7, 0x5d, 0xa3, 0xfa, 0x65, 0xc6, 0x7e, 0x48, 0x52, 0xe8, 0xd8, 0xbb,
	0x3b, 0x75, 0xd8, 0xc3, 0x8f, 0x67, 0x7b, 0xef, 0x56, 0x25, 0x37, 0xc7, 0xee, 0xeb, 0xbf, 0xf8,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x18, 0x5d, 0x68, 0xf8, 0xb3, 0x03, 0x00, 0x00,
}
