#!/bin/sh

ROOT_DIR=$(pwd)
FRONTEND_DIR="${ROOT_DIR}/frontend"
BASE_GIT_DIFF_CMD="git diff --name-only --staged --relative=frontend"

if [[ $(${BASE_GIT_DIFF_CMD} -- frontend) ]]; then
  echo "Running frontend checks in ${FRONTEND_DIR}..."
  cd "${FRONTEND_DIR}"

  if [[ $(${BASE_GIT_DIFF_CMD} -- **/**/package.json) ]]; then
    echo "\nLinting frontend packages...\n"
    {
      yarn lint:packages
    } || {
      echo "\n${FRONTEND_DIR} package lint checks failed, please run \"yarn lint:packages:fix\" and commit the changes."
      exit 1
    }

    echo "\nTesting frontend package constraints...\n"
    {
      yarn constraints
    } || {
      echo "\n${FRONTEND_DIR} constraints check failed, please run \"yarn constraints --fix\" and commit the changes."
      exit 1
    }
  fi

  STAGED_FILES=$(${BASE_GIT_DIFF_CMD} -- **/**/src)
  if [[ ${STAGED_FILES} ]]; then
    echo "\nLinting frontend code..."
    {
      yarn lint:files ${STAGED_FILES}
    } || {
      echo "\n${FRONTEND_DIR} lint checks failed, please try running \"yarn lint:fix\" and committing the changes."
      exit 1
    }

    echo "\nRunning frontend tests..."
    {
      yarn test:coverage
    } || {
      echo "\n${FRONTEND_DIR} tests failed, please fix the issues and commit the changes."
      exit 1
    }
  fi
fi

exit 0
