// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: config/service/auditsink/slack/v1/slack.proto

package slackv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	v1 "github.com/lyft/clutch/backend/api/config/service/audit/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SlackConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string           `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Channel   string           `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Filter    *v1.Filter       `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Overrides []*CustomMessage `protobuf:"bytes,4,rep,name=overrides,proto3" json:"overrides,omitempty"`
}

func (x *SlackConfig) Reset() {
	*x = SlackConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_service_auditsink_slack_v1_slack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlackConfig) ProtoMessage() {}

func (x *SlackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_auditsink_slack_v1_slack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlackConfig.ProtoReflect.Descriptor instead.
func (*SlackConfig) Descriptor() ([]byte, []int) {
	return file_config_service_auditsink_slack_v1_slack_proto_rawDescGZIP(), []int{0}
}

func (x *SlackConfig) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SlackConfig) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SlackConfig) GetFilter() *v1.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *SlackConfig) GetOverrides() []*CustomMessage {
	if x != nil {
		return x.Overrides
	}
	return nil
}

//
//By default, the sink provides a formatted message using a subset of info in an audit event. A custom
//message can alo be created for a `/SERVICE/METHOD` using the metadata (API Request/Response) in an
//audit event. The custom message will be appened to the default message for a richer slack audit.
type CustomMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The full method in the format of `/SERVICE/METHOD`
	FullMethod string `protobuf:"bytes,1,opt,name=full_method,json=fullMethod,proto3" json:"full_method,omitempty"`
	//
	//The slack sink uses the Go text/template pacakge. Example of a custom message for /clutch.k8s.v1.K8sAPI/ResizeHPA:
	//"{{Min size: $$Request.sizing.min\nMax size: $$Request.sizing.max}}"
	//See https://api.slack.com/reference/surfaces/formatting for Slack markdown formatting
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CustomMessage) Reset() {
	*x = CustomMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_service_auditsink_slack_v1_slack_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomMessage) ProtoMessage() {}

func (x *CustomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_config_service_auditsink_slack_v1_slack_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomMessage.ProtoReflect.Descriptor instead.
func (*CustomMessage) Descriptor() ([]byte, []int) {
	return file_config_service_auditsink_slack_v1_slack_proto_rawDescGZIP(), []int{1}
}

func (x *CustomMessage) GetFullMethod() string {
	if x != nil {
		return x.FullMethod
	}
	return ""
}

func (x *CustomMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_config_service_auditsink_slack_v1_slack_proto protoreflect.FileDescriptor

var file_config_service_auditsink_slack_v1_slack_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x73, 0x69, 0x6e, 0x6b, 0x2f, 0x73, 0x6c, 0x61, 0x63, 0x6b,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x28, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x74, 0x73, 0x69, 0x6e, 0x6b,
	0x2e, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x1a, 0x23, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2f,
	0x76, 0x31, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe6, 0x01, 0x0a, 0x0b, 0x53, 0x6c, 0x61, 0x63,
	0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x20, 0x01, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x20, 0x01,
	0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x3e, 0x0a, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x6c, 0x75, 0x74,
	0x63, 0x68, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x55, 0x0a, 0x09, 0x6f, 0x76, 0x65,
	0x72, 0x72, 0x69, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x63,
	0x6c, 0x75, 0x74, 0x63, 0x68, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x74, 0x73, 0x69, 0x6e, 0x6b, 0x2e, 0x73,
	0x6c, 0x61, 0x63, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x09, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x73,
	0x22, 0x5c, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x28, 0x0a, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x20, 0x01, 0x52,
	0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x21, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x20, 0x01, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x4e,
	0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x79, 0x66,
	0x74, 0x2f, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74, 0x73, 0x69, 0x6e, 0x6b, 0x2f, 0x73, 0x6c,
	0x61, 0x63, 0x6b, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_service_auditsink_slack_v1_slack_proto_rawDescOnce sync.Once
	file_config_service_auditsink_slack_v1_slack_proto_rawDescData = file_config_service_auditsink_slack_v1_slack_proto_rawDesc
)

func file_config_service_auditsink_slack_v1_slack_proto_rawDescGZIP() []byte {
	file_config_service_auditsink_slack_v1_slack_proto_rawDescOnce.Do(func() {
		file_config_service_auditsink_slack_v1_slack_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_service_auditsink_slack_v1_slack_proto_rawDescData)
	})
	return file_config_service_auditsink_slack_v1_slack_proto_rawDescData
}

var file_config_service_auditsink_slack_v1_slack_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_service_auditsink_slack_v1_slack_proto_goTypes = []interface{}{
	(*SlackConfig)(nil),   // 0: clutch.config.service.auditsink.slack.v1.SlackConfig
	(*CustomMessage)(nil), // 1: clutch.config.service.auditsink.slack.v1.CustomMessage
	(*v1.Filter)(nil),     // 2: clutch.config.service.audit.v1.Filter
}
var file_config_service_auditsink_slack_v1_slack_proto_depIdxs = []int32{
	2, // 0: clutch.config.service.auditsink.slack.v1.SlackConfig.filter:type_name -> clutch.config.service.audit.v1.Filter
	1, // 1: clutch.config.service.auditsink.slack.v1.SlackConfig.overrides:type_name -> clutch.config.service.auditsink.slack.v1.CustomMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_config_service_auditsink_slack_v1_slack_proto_init() }
func file_config_service_auditsink_slack_v1_slack_proto_init() {
	if File_config_service_auditsink_slack_v1_slack_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_service_auditsink_slack_v1_slack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlackConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_service_auditsink_slack_v1_slack_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_service_auditsink_slack_v1_slack_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_service_auditsink_slack_v1_slack_proto_goTypes,
		DependencyIndexes: file_config_service_auditsink_slack_v1_slack_proto_depIdxs,
		MessageInfos:      file_config_service_auditsink_slack_v1_slack_proto_msgTypes,
	}.Build()
	File_config_service_auditsink_slack_v1_slack_proto = out.File
	file_config_service_auditsink_slack_v1_slack_proto_rawDesc = nil
	file_config_service_auditsink_slack_v1_slack_proto_goTypes = nil
	file_config_service_auditsink_slack_v1_slack_proto_depIdxs = nil
}
