// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: config/middleware/accesslog/v1/accesslog.proto

package accesslogv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// if no filter is specified all status codes are logged
	StatusCodeFilters []*Config_StatusCodeFilter `protobuf:"bytes,1,rep,name=status_code_filters,json=statusCodeFilters,proto3" json:"status_code_filters,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_middleware_accesslog_v1_accesslog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_middleware_accesslog_v1_accesslog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_middleware_accesslog_v1_accesslog_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetStatusCodeFilters() []*Config_StatusCodeFilter {
	if x != nil {
		return x.StatusCodeFilters
	}
	return nil
}

// filter on an interger comparison of the status code
type Config_StatusCodeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// only equals filter type is supported for now
	// since there are only 16 codes for gRPC. We can
	// expand this to include a range filter type if need be.
	//
	// Types that are assignable to FilterType:
	//	*Config_StatusCodeFilter_Equals
	FilterType isConfig_StatusCodeFilter_FilterType `protobuf_oneof:"filter_type"`
}

func (x *Config_StatusCodeFilter) Reset() {
	*x = Config_StatusCodeFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_middleware_accesslog_v1_accesslog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_StatusCodeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_StatusCodeFilter) ProtoMessage() {}

func (x *Config_StatusCodeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_config_middleware_accesslog_v1_accesslog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_StatusCodeFilter.ProtoReflect.Descriptor instead.
func (*Config_StatusCodeFilter) Descriptor() ([]byte, []int) {
	return file_config_middleware_accesslog_v1_accesslog_proto_rawDescGZIP(), []int{0, 0}
}

func (m *Config_StatusCodeFilter) GetFilterType() isConfig_StatusCodeFilter_FilterType {
	if m != nil {
		return m.FilterType
	}
	return nil
}

func (x *Config_StatusCodeFilter) GetEquals() uint32 {
	if x, ok := x.GetFilterType().(*Config_StatusCodeFilter_Equals); ok {
		return x.Equals
	}
	return 0
}

type isConfig_StatusCodeFilter_FilterType interface {
	isConfig_StatusCodeFilter_FilterType()
}

type Config_StatusCodeFilter_Equals struct {
	// gRPC status code value
	Equals uint32 `protobuf:"varint,1,opt,name=equals,proto3,oneof"`
}

func (*Config_StatusCodeFilter_Equals) isConfig_StatusCodeFilter_FilterType() {}

var File_config_middleware_accesslog_v1_accesslog_proto protoreflect.FileDescriptor

var file_config_middleware_accesslog_v1_accesslog_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77,
	0x61, 0x72, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x25, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xc0, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x6e, 0x0a, 0x13, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x63, 0x6c, 0x75, 0x74, 0x63,
	0x68, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77,
	0x61, 0x72, 0x65, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6c, 0x6f, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x46, 0x0a, 0x10, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x23, 0x0a, 0x06, 0x65, 0x71, 0x75, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42,
	0x09, 0xfa, 0x42, 0x06, 0x2a, 0x04, 0x18, 0x10, 0x28, 0x00, 0x48, 0x00, 0x52, 0x06, 0x65, 0x71,
	0x75, 0x61, 0x6c, 0x73, 0x42, 0x0d, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x79, 0x66, 0x74, 0x2f, 0x63, 0x6c, 0x75, 0x74, 0x63, 0x68, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x6c, 0x6f, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6c,
	0x6f, 0x67, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_middleware_accesslog_v1_accesslog_proto_rawDescOnce sync.Once
	file_config_middleware_accesslog_v1_accesslog_proto_rawDescData = file_config_middleware_accesslog_v1_accesslog_proto_rawDesc
)

func file_config_middleware_accesslog_v1_accesslog_proto_rawDescGZIP() []byte {
	file_config_middleware_accesslog_v1_accesslog_proto_rawDescOnce.Do(func() {
		file_config_middleware_accesslog_v1_accesslog_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_middleware_accesslog_v1_accesslog_proto_rawDescData)
	})
	return file_config_middleware_accesslog_v1_accesslog_proto_rawDescData
}

var file_config_middleware_accesslog_v1_accesslog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_middleware_accesslog_v1_accesslog_proto_goTypes = []interface{}{
	(*Config)(nil),                  // 0: clutch.config.middleware.accesslog.v1.Config
	(*Config_StatusCodeFilter)(nil), // 1: clutch.config.middleware.accesslog.v1.Config.StatusCodeFilter
}
var file_config_middleware_accesslog_v1_accesslog_proto_depIdxs = []int32{
	1, // 0: clutch.config.middleware.accesslog.v1.Config.status_code_filters:type_name -> clutch.config.middleware.accesslog.v1.Config.StatusCodeFilter
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_middleware_accesslog_v1_accesslog_proto_init() }
func file_config_middleware_accesslog_v1_accesslog_proto_init() {
	if File_config_middleware_accesslog_v1_accesslog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_middleware_accesslog_v1_accesslog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_middleware_accesslog_v1_accesslog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_StatusCodeFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_config_middleware_accesslog_v1_accesslog_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Config_StatusCodeFilter_Equals)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_middleware_accesslog_v1_accesslog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_middleware_accesslog_v1_accesslog_proto_goTypes,
		DependencyIndexes: file_config_middleware_accesslog_v1_accesslog_proto_depIdxs,
		MessageInfos:      file_config_middleware_accesslog_v1_accesslog_proto_msgTypes,
	}.Build()
	File_config_middleware_accesslog_v1_accesslog_proto = out.File
	file_config_middleware_accesslog_v1_accesslog_proto_rawDesc = nil
	file_config_middleware_accesslog_v1_accesslog_proto_goTypes = nil
	file_config_middleware_accesslog_v1_accesslog_proto_depIdxs = nil
}
