name: docker-dev
on:
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: determine tags
        id: tags
        run: |
          DOCKER_IMAGE=lyft/clutch
          VERSION=latest
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::7}"
          echo ::set-output name=tags::${TAGS}
      - name: build
        uses: docker/build-push-action@v2.7.0
        with:
          tags: ${{ steps.tags.outputs.tags }}
          push: false
          cache-from: type=registry,ref=lyft/clutch:latest
