on:
# TODO: need pull?
  pull_request:
      branches:
      # TODO: is this for a pull request intended to be merged on main branch?
      - main
    paths:
    # TODO: refernce the workfow itself? reference backend/**
      - backend/go.mod
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
      - name: Setup Ruby 2.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.x
      - name: Install license finder
        run: gem install license_finder
      - name: Run license finder
        run: license_finder