# If the job fails, see clutch/tools/license-finder for instructions on approving a dependency.
name: license_review
on:
  pull_request:
    branches:
     - main
    paths:
      - backend/go.mod
      - backend/go.sum
      - .github/workflows/license_review.yml
jobs:
  license-check:
    runs-on: ubuntu-latest
    env:
      working-directory: ./tools/license-finder
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install license finder
        run: gem install license_finder
      - name: Run license finder
        run: license_finder
        working-directory: ${{env.working-directory}}